# Generated by Django 2.1 on 2020-08-22 02:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cnum', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10, unique=True, verbose_name='类别')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comnum', models.AutoField(primary_key=True, serialize=False)),
                ('commentcontent', models.TextField(verbose_name='评论内容')),
            ],
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('lnum', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='题目')),
                ('content', models.TextField(verbose_name='内容')),
                ('createdTime', models.DateTimeField(default=datetime.datetime(2020, 8, 22, 2, 56, 0, 545589, tzinfo=utc), verbose_name='创建时间')),
                ('categories', models.ManyToManyField(to='learning_log.Category', verbose_name='类型')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='learning_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_log.LearningContent', verbose_name='所有贴'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
    ]
