# Generated by Django 2.1 on 2020-08-26 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='private',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='createdTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_log', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
    ]
