# Generated by Django 2.1 on 2020-08-26 10:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0003_auto_20200826_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontent',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
